#!/usr/bin/env python3
"""
TRAC-IK Workspace Reachability & Failure Map Plotter

Reads ik_workspace_map.csv generated by trac_ik_benchmark and plots
2D heatmap slices (radial reach r vs elevation z) for each world_pitch slice.
Overlays operational limits from ps5_mapper as dashed cyan rectangles.
"""

import sys
import os
import csv
from collections import defaultdict
import numpy as np
import matplotlib
matplotlib.use("Agg")  # Headless backend
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.patches import Rectangle


def main():
    csv_file = sys.argv[1] if len(sys.argv) > 1 else "ik_workspace_map.csv"
    if not os.path.exists(csv_file):
        print(f"[ERROR] CSV file '{csv_file}' not found. Run trac_ik_benchmark with workspace_map:=true first.")
        sys.exit(1)

    print(f"[INFO] Reading workspace map data from: {csv_file}")
    
    # Read CSV data: rows of (r, z, world_pitch, success_rate, n_success, n_attempts)
    data_by_pitch = defaultdict(dict)  # pitch_key -> {(r, z): success_rate}
    all_pitches = set()
    all_r = set()
    all_z = set()

    with open(csv_file, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            r = float(row["r"])
            z = float(row["z"])
            pitch = float(row["world_pitch"])
            sr = float(row["success_rate"])

            # Round pitch to 3 decimal places to group reliably
            p_key = round(pitch, 3)
            all_pitches.add(p_key)
            all_r.add(r)
            all_z.add(z)
            data_by_pitch[p_key][(round(r, 4), round(z, 4))] = sr

    sorted_pitches = sorted(all_pitches)
    sorted_r = sorted(all_r)
    sorted_z = sorted(all_z)
    num_pitches = len(sorted_pitches)

    print(f"[INFO] Found {num_pitches} pitch slices across {len(sorted_r)} r steps and {len(sorted_z)} z steps.")

    # Subplot grid layout
    cols = min(4, num_pitches)
    rows = (num_pitches + cols - 1) // cols

    fig, axes = plt.subplots(rows, cols, figsize=(5.5 * cols, 4.5 * rows), squeeze=False)
    axes_flat = axes.flatten()

    cmap = plt.cm.RdYlGn
    norm = mcolors.Normalize(vmin=0.0, vmax=1.0)

    # Operational limits from ps5_mapper
    op_r_min, op_r_max = 0.10, 1.10
    op_z_min, op_z_max = -0.60, 1.20

    r_map = {round(val, 4): idx for idx, val in enumerate(sorted_r)}
    z_map = {round(val, 4): idx for idx, val in enumerate(sorted_z)}

    for i, p_key in enumerate(sorted_pitches):
        grid = np.full((len(sorted_z), len(sorted_r)), np.nan)
        slice_data = data_by_pitch[p_key]

        for (r_val, z_val), sr in slice_data.items():
            r_idx = r_map.get(r_val)
            z_idx = z_map.get(z_val)
            if r_idx is not None and z_idx is not None:
                grid[z_idx, r_idx] = sr

        ax = axes_flat[i]
        im = ax.imshow(
            grid,
            origin="lower",
            aspect="auto",
            cmap=cmap,
            norm=norm,
            extent=[min(sorted_r), max(sorted_r), min(sorted_z), max(sorted_z)],
            interpolation="nearest"
        )

        pitch_deg = np.degrees(p_key)
        reachable_count = sum(1 for v in slice_data.values() if v > 0.0)
        total_count = len(slice_data)
        pct = (reachable_count / total_count * 100.0) if total_count > 0 else 0.0

        ax.set_title(
            f"world_pitch = {p_key:.2f} rad ({pitch_deg:+.0f}°)\nReachability: {reachable_count}/{total_count} ({pct:.1f}%)",
            fontsize=10,
            fontweight="bold"
        )
        ax.set_xlabel("Reach r (m)", fontsize=10)
        ax.set_ylabel("Elevation z (m)", fontsize=10)
        ax.grid(True, linestyle=":", alpha=0.5, color="gray")

        # Overlay old rectangular operational limits
        rect = Rectangle(
            (op_r_min, op_z_min),
            op_r_max - op_r_min,
            op_z_max - op_z_min,
            linewidth=1.4,
            edgecolor="cyan",
            facecolor="none",
            linestyle="--",
            label="Old Rectangular Limits"
        )
        ax.add_patch(rect)

        # Overlay new spherical workspace envelope
        z_curve = np.linspace(op_z_min, op_z_max, 200)
        z_rel = z_curve - 0.20
        r_curve = np.sqrt(np.maximum(0.0, 1.10**2 - z_rel**2))
        r_curve = np.minimum(r_curve, op_r_max)
        ax.plot(r_curve, z_curve, color="magenta", linewidth=2.0, linestyle="-", label="New Spherical Envelope")

        # Plot home position mark (r ~ 0.70, z ~ 0.21)
        ax.plot(0.70, 0.21, marker="*", color="blue", markersize=9, label="Home Pose (tool0)")

        if i == 0:
            ax.legend(loc="upper left", fontsize=7.5, framealpha=0.85)

    # Hide unused subplots
    for j in range(num_pitches, len(axes_flat)):
        axes_flat[j].set_visible(False)

    cbar = fig.colorbar(
        plt.cm.ScalarMappable(norm=norm, cmap=cmap),
        ax=axes_flat[:num_pitches].tolist(),
        label="IK Success Rate (0.0 = Fail, 1.0 = 100% Success)",
        shrink=0.7,
        pad=0.03
    )

    fig.suptitle(
        "TRAC-IK Cartesian Reachability & Failure Map\n(Full Physical Workspace vs. Operational Envelope)",
        fontsize=14,
        fontweight="bold"
    )

    out_png = "ik_workspace_map.png"
    plt.tight_layout()
    plt.savefig(out_png, dpi=150, bbox_inches="tight")
    print(f"[SUCCESS] Heatmap figure saved to: {os.path.abspath(out_png)}")


if __name__ == "__main__":
    main()
